### ISSUE TITLE
Paginate search results

### ISSUE THREAD

**Issue by JJRcop** [vinifmor/bauh#331] opened 2023-09-24 00:22 UTC
**Describe the suggestion**
When searching, bauh should paginate the results based on the set limit rather than show only up to the limit and stop, not letting you continue.

This could also just be a "Show More" button to show the next (for example) 50 results, whichever design you like better.

**Software Environment**
bauh version: 0.10.6-staging
O.S: Debian 13 trixie (testing)
Python version: 3.11.5
Installation method: pipx and git from staging branch

![Screenshot_20230924_032206](https://github.com/vinifmor/bauh/assets/5211576/56948f70-519a-4e45-8111-98fe2ad81c26)

**Comment by vinifmor** [comment] 2023-10-08 14:29
Hi @JJRcop , this suggestion is a duplicate of https://github.com/vinifmor/bauh/issues/124. I'll be closing this issue, and link it with the first.

**Closed by vinifmor** 2023-10-08 14:29 UTC

**Comment by JJRcop** [comment] 2023-10-08 17:25
Thank you, I missed that one
